### ISSUE TITLE
Not compatible with WHMCS 7.1

### ISSUE THREAD

**Issue by petzsch** [EnduranceIndia/whmcs-resellerclub-modules#25]
When wanting to create a new server I get the following:

Fatal error: Cannot redeclare _get_order_details() (previously declared in /var/www/clients/client3/web6/web/modules/servers/resellerclubmdhostinghk/resellerclubmdhostinghk.php:589) in /var/www/clients/client3/web6/web/modules/servers/resellerclubvpsus/resellerclubvpsus.php on line 567

**Comment by petzsch** [comment]
Doesn't work with 7.0.1 either :-(
As soon as I click on "Add new Server" I get the error message.

**Comment by viral-patel** [comment]
@petzsch : this issue has been fixed already.
https://github.com/EnduranceIndia/whmcs-resellerclub-modules/issues/22

Can you re-download package or download and use latest version of modules/servers/resellerclubvpsus/resellerclubvpsus.php file ?

Confirm if this resolves your issue.

**Comment by petzsch** [comment]
I've redownloaded https://github.com/EnduranceIndia/whmcs-resellerclub-modules/archive/master.zip and the error is still present:


Fatal error: Cannot redeclare _get_order_details() (previously declared in /var/www/clients/client3/web6/web/modules/servers/resellerclubmdhostinghk/resellerclubmdhostinghk.php:589) in /var/www/clients/client3/web6/web/modules/servers/resellerclubvpsus/resellerclubvpsus.php on line 567

**Comment by viral-patel** [comment]
@petzsch : Pull latest code / Use latest version of modules/servers/resellerclubvpsus/resellerclubvpsus.php file.

Confirm if this resolves your issue.

**Comment by petzsch** [comment]
It seem to work now. I've been able to create the server and add a product. haven't tried ordering it yet.
